In [3]:
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
from scipy import stats
import pandas as pd
import math

<h1>RIVERS</h1>

In [4]:
with open('rivers.txt') as file:
    lines = file.readlines()

In [5]:
pacific_list = list()
tasman_list = list()
for line in lines:
    line = line.replace('\t', ' ' )
    line = line.replace('\n', '')
    line = line.split(' ')
    if line[2] == 'Pacific':
        pacific_list.append(float(line[1]))
    elif line[2] == 'Tasman':
        tasman_list.append(float(line[1]))
tasman_list = np.array(tasman_list)
pacific_list = np.array(pacific_list)

In [110]:
tasman_list.shape, pacific_list.shape

((22,), (19,))

In [111]:
tasman_list.mean(), pacific_list.mean()

(67.68181818181819, 131.1578947368421)

In [24]:
stats.mannwhitneyu(tasman_list, pacific_list, alternative='greater')

MannwhitneyuResult(statistic=87.0, pvalue=0.9993378552933345)

In [25]:
stats.ks_2samp(tasman_list, pacific_list, alternative='less')

KstestResult(statistic=0.0, pvalue=1.0)

<h1>IRIS</h1>

In [2]:
import pandas as pd
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data",
                 names = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species'])
print(df.head())

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa


In [77]:
iris_setosa = list()
iris_versicolor = list()
iris_virginica = list()

for index, row in df.iterrows():
    lst = [row['SepalLengthCm'], row['SepalWidthCm'], row['PetalLengthCm'], 
          row['PetalWidthCm']]
    if row['Species'] == 'Iris-setosa':
        iris_setosa.append(lst)
    elif row['Species'] == 'Iris-versicolor':
        iris_versicolor.append(lst)
    elif row['Species'] == 'Iris-virginica':
        iris_virginica.append(lst)

In [30]:
from hyppo.ksample import KSample

criterion = 'HHG'

In [31]:
ksample = KSample(criterion).test(np.array(iris_setosa), np.array(iris_versicolor)
                    ,np.array(iris_virginica))
ksample.pvalue

0.000999000999000999

In [32]:
ksample = KSample(criterion).test(np.array(iris_setosa), np.array(iris_versicolor))
ksample.pvalue

0.000999000999000999

In [33]:
ksample = KSample(criterion).test(np.array(iris_setosa), np.array(iris_virginica))
ksample.pvalue

0.000999000999000999

In [34]:
ksample = KSample(criterion).test(np.array(iris_versicolor), np.array(iris_virginica))
ksample.pvalue

0.000999000999000999

In [35]:
1/1001

0.000999000999000999

In [36]:
criterion = 'Hsic'

In [37]:
ksample = KSample(criterion).test(np.array(iris_setosa), np.array(iris_versicolor)
                    ,np.array(iris_virginica))
ksample.pvalue

9.281903157161839e-27

In [38]:
ksample = KSample(criterion).test(np.array(iris_setosa), np.array(iris_virginica))
ksample.pvalue

2.4524973332059437e-23

In [39]:
ksample = KSample(criterion).test(np.array(iris_setosa), np.array(iris_versicolor))
ksample.pvalue

6.96691701692607e-23

In [40]:
ksample = KSample(criterion).test(np.array(iris_versicolor), np.array(iris_virginica))
ksample.pvalue

5.239294618609153e-15

<h1>MEAN</h1>

In [42]:
from hyppo.ksample import MANOVA

ksample = MANOVA().test(np.array(iris_setosa), np.array(iris_versicolor)
                    ,np.array(iris_virginica))
ksample.pvalue

5.86094394827863e-32

In [ ]:
ksample = MANOVA().test(np.array(iris_setosa), np.array(iris_versicolor))
ksample.pvalue

4.848110016202354e-38

In [45]:
ksample = MANOVA().test(np.array(iris_setosa), np.array(iris_virginica))
ksample.pvalue

8.427091717292316e-48

In [48]:
ksample = MANOVA().test(np.array(iris_versicolor), np.array(iris_virginica))
ksample.pvalue

1.9308765971414464e-12

In [79]:
iris_setosa = np.array(iris_setosa)
iris_virginica = np.array(iris_virginica)
iris_versicolor = np.array(iris_versicolor)

In [80]:
iris_setosa.mean(axis=0), iris_virginica.mean(axis=0), iris_versicolor.mean(axis=0)

(array([5.006, 3.418, 1.464, 0.244]),
 array([6.588, 2.974, 5.552, 2.026]),
 array([5.936, 2.77 , 4.26 , 1.326]))

<h1>POISON</h1

In [115]:
with open('poisson.txt') as file:
    lines = file.readlines()

In [120]:

col0 = list()
col1 = list()
col2 = list()

for line in lines[1:]:
    line = line.replace('\t', ' ' )
    line = line.replace('\n', '')
    lst = line.split(' ')
    
    col0.append(int(lst[0]))
    col1.append(int(lst[1]))
    col2.append(float(lst[2]))

In [124]:
df = pd.DataFrame({'drug': col0,
                   'cure': col1,
                   'time': col2})

In [128]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

#perform two-way ANOVA
model = ols('time ~ C(drug) + C(cure) + C(drug):C(cure)', data=df).fit()
sm.stats.anova_lm(model, typ=2)

sum_sq    df          F        PR(>F)
C(drug)          1.033012   2.0  23.221737  3.331440e-07
C(cure)          0.921206   3.0  13.805582  3.777331e-06
C(drug):C(cure)  0.250138   6.0   1.874333  1.122506e-01
Residual         0.800725  36.0        NaN           NaN